name: Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - dev

jobs:
  test:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Check out code
        uses: actions/checkout@v2

      - name: Lint Go Code
        run: |
          go install golang.org/x/lint/golint@latest
          golint -set_exit_status github.com/taouniverse/tao

      - name: Run Unit tests.
        run: ./test.sh

      - name: Upload Coverage report to CodeCov
        uses: codecov/codecov-action@v2
        with:
          token: a4d7ebb0-3ea0-4727-ad2e-6f75fd938375
          file: ./coverage.txt
